# Generated by Django 4.0.3 on 2022-04-10 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordofmouth', '0008_recipe_directions'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='staticfiles/recipe.png', upload_to='staticfiles'),
        ),
    ]
