# Generated by Django 4.0.4 on 2022-04-18 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordofmouth', '0010_comments_active'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
