# Generated by Django 4.0.3 on 2022-04-28 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordofmouth', '0014_comment'),
        ('wordofmouth', '0014_forkedrecipe'),
    ]

    operations = [
    ]
