# Generated by Django 4.0.3 on 2022-04-29 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordofmouth', '0016_rename_originalrecipe_forkedrecipe_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='parent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ForkedRecipe',
        ),
    ]
